site_name: Kurs Microsoft Teams dla pracowników firmy
site_author: Cyprian Wlezień, Jakub Zabawa

theme:
    name: readthedocs
    language: pl

repo_url: https://github.com/Cyprian-Wlezien/MicrosoftTeams_Dokumentacja-dev


nav:
  - Strona główna: index.md
  - modul1.md
  - modul2.md
  - modul3.md
  - modul4.md
  - modul5.md
  - modul6.md
  - modul7.md
  - modul8.md
  - podsumowanie.md
  - autorzy.md